name: the-powder-toy
base: core24
version: '98.2'
summary: An opensource 2D physics simulation game!
description: |
  The Powder Toy is a free physics sandbox game, which simulates air pressure and velocity, heat, gravity and a countless number of interactions between different substances!
  The game provides you with various building materials, liquids, gases and electronic components which can be used to construct complex machines, guns, bombs, realistic terrains and almost anything else.
  You can then mine them and watch cool explosions, add intricate wirings, play with little stickmen or operate your machine.
  You can browse and play thousands of different saves made by the community or upload your own.

grade: stable
confinement: strict
license: GPL-3.0

parts:
  the-powder-toy:
    plugin: meson
    source: https://github.com/the-powder-toy/the-powder-toy.git
    source-type: git
    source-commit: e371d6345b620e961417f0950d19f7df525df7dd # 98.2.365
    meson-parameters:
      - -Dbuildtype=release
      - -Dstatic=none
      - -Dignore_updates=true
      - -Dcan_install=no
    build-packages:
      - libbz2-dev
      - libluajit-5.1-dev
      - libfftw3-dev
      - libsdl2-dev
      - libjsoncpp-dev
    override-build: |
      craftctl default
      mkdir -p ${CRAFT_PART_INSTALL}/bin
      cp ${CRAFT_PART_BUILD}/powder ${CRAFT_PART_INSTALL}/bin/powder
    stage-packages:
      - libsdl2-2.0-0
      - libxss1
      - libdecor-0-0
      - libfftw3-single3
      - libjsoncpp25
      - libluajit-5.1-2
      - libsamplerate0

apps:
  the-powder-toy:
    command: bin/powder
    plugs:
      - network
    extensions: [gnome]
